import requests
import time
from google import genai
from google.genai import types

# ==========================================
# 1. CONFIGURATION
# ==========================================
NEWS_API_KEY = "INSERET KEY HERE"
GEMINI_API_KEY = "INSERET KEY HERE"

# MODELS
PRIMARY_MODEL = "gemini-3-flash-preview"  # Smart but unstable
BACKUP_MODEL = "gemini-2.0-flash"         # Fast and reliable

# ==========================================
# 2. DATA TOOLS (RAG)
# ==========================================
def get_football_stats(team_name):
    return f"Next match for {team_name} is coming up soon."

def get_news_gossip(team_name):
    url = "https://newsapi.org/v2/everything"
    params = {
        "q": f'"{team_name}" AND (football OR "Premier League")',
        "sortBy": "publishedAt",
        "language": "en",
        "pageSize": 3,
        "apiKey": NEWS_API_KEY
    }
    try:
        r = requests.get(url, params=params)
        data = r.json()
        articles = [f"- {a['title']}" for a in data.get("articles", [])]
        return "\n".join(articles)
    except:
        return "No news found."

# ==========================================
# 3. ROBUST CHAT ENGINE
# ==========================================
def create_chat_session(client, model_name, system_instr):
    """Helper to create a new chat session with a specific model"""
    return client.chats.create(
        model=model_name,
        config=types.GenerateContentConfig(
            system_instruction=system_instr,
            temperature=0.7
        )
    )

def run_bluffball():
    client = genai.Client(api_key=GEMINI_API_KEY)
    
    user_team = input("Which team are we bluffing about? ").strip()
    
    # 1. Load Context
    hard_facts = get_football_stats(user_team)
    soft_news = get_news_gossip(user_team)
    
    system_instruction = f"""
    You are 'Bluffball'. 
    CONTEXT: {hard_facts}
    NEWS: {soft_news}
    INSTRUCTIONS: Be a casual {user_team} fan. Keep it short.
    """

    # 2. Initialize Primary Model
    current_model = PRIMARY_MODEL
    print(f"\n🚀 Initializing with {current_model}...")
    chat = create_chat_session(client, current_model, system_instruction)
    
    print(f"✅ READY. You are a fake {user_team.upper()} expert.\n")

    while True:
        msg = input("[Friend]: ")
        if msg.lower() in ['quit', 'exit']: break
        
        # 3. The "Safe Send" Logic
        try:
            # Attempt 1: Try the current (fancy) model
            response = chat.send_message(msg)
            print(f"[You]   : {response.text}\n")
            
        except Exception as e:
            # If it fails (503, 429, etc.)
            print(f"\n⚠️  Error with {current_model}: {e}")
            print(f"🔄 Switching to Backup Model ({BACKUP_MODEL})...")
            
            # Switch the 'current_model' variable
            current_model = BACKUP_MODEL
            
            # Re-create the chat session with the stable model
            # (Note: We lose previous history here, but we save the app from crashing)
            chat = create_chat_session(client, current_model, system_instruction)
            
            # Retry the SAME message automatically
            try:
                response = chat.send_message(msg)
                print(f"[You]   : {response.text} (Generated by Backup)\n")
            except Exception as e2:
                print(f"❌ Backup failed too. The internet is broken.\n")

if __name__ == "__main__":
    run_bluffball()